// Generated by the lua-protobuf compiler
// You shouldn't edit this file manually
// source proto file: connectionType.proto
#include "connectionType.lua.h"
#include <lua/lua.hpp>
#include <string>
#include <sstream>
#include <set>
#include <boost/cast.hpp>
extern int udataNum;
extern std::set< ::google::protobuf::Message*> u_datas;


namespace { bool success = AddOpenFunction(lua_protobuf_pb_open); }
int lua_protobuf_pb_open(lua_State *L)
{
    const char *table = luaL_findtable(L, LUA_GLOBALSINDEX, "proto-buf.pb", 1);
    if (table) {
        return luaL_error(L, "could not create parent Lua tables");
    }
    if (!lua_istable(L, -1)) {
        lua_newtable(L);
        lua_setfield(L, -2, "pb");
    }
    lua_pop(L, 1);
    luaL_Reg funcs [] = { { NULL, NULL } };
    luaL_register(L, "proto-buf.pb", funcs);
    return 1;
}

