// Generated by the lua-protobuf compiler.
// You shouldn't be editing this file manually
//
// source proto file: connectionType.proto
#pragma once

#include "lua-protobuf.h"
#include "connectionType.pb.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <lua/lua.h>

#ifdef __cplusplus
}

// register all messages in this package to a Lua state
static int lua_protobuf_pb_open(lua_State *L);

#endif