// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

#ifndef PROTOBUF_header_2eproto__INCLUDED
#define PROTOBUF_header_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_header_2eproto();
void protobuf_AssignDesc_header_2eproto();
void protobuf_ShutdownFile_header_2eproto();

class Header;

// ===================================================================

class Header : public ::google::protobuf::Message {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Header& default_instance();

  void Swap(Header* other);

  // implements Message ----------------------------------------------

  Header* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 packetID = 1;
  inline bool has_packetid() const;
  inline void clear_packetid();
  static const int kPacketIDFieldNumber = 1;
  inline ::google::protobuf::int32 packetid() const;
  inline void set_packetid(::google::protobuf::int32 value);

  // optional int32 packetSize = 2;
  inline bool has_packetsize() const;
  inline void clear_packetsize();
  static const int kPacketSizeFieldNumber = 2;
  inline ::google::protobuf::int32 packetsize() const;
  inline void set_packetsize(::google::protobuf::int32 value);

  // optional uint32 sourceGuid = 3;
  inline bool has_sourceguid() const;
  inline void clear_sourceguid();
  static const int kSourceGuidFieldNumber = 3;
  inline ::google::protobuf::uint32 sourceguid() const;
  inline void set_sourceguid(::google::protobuf::uint32 value);

  // optional uint32 playerID = 4;
  inline bool has_playerid() const;
  inline void clear_playerid();
  static const int kPlayerIDFieldNumber = 4;
  inline ::google::protobuf::uint32 playerid() const;
  inline void set_playerid(::google::protobuf::uint32 value);

  // optional uint32 gateGuid = 5;
  inline bool has_gateguid() const;
  inline void clear_gateguid();
  static const int kGateGuidFieldNumber = 5;
  inline ::google::protobuf::uint32 gateguid() const;
  inline void set_gateguid(::google::protobuf::uint32 value);

  // optional uint32 playerGuid = 6;
  inline bool has_playerguid() const;
  inline void clear_playerguid();
  static const int kPlayerGuidFieldNumber = 6;
  inline ::google::protobuf::uint32 playerguid() const;
  inline void set_playerguid(::google::protobuf::uint32 value);

  // repeated uint32 remoteGuids = 7;
  inline int remoteguids_size() const;
  inline void clear_remoteguids();
  static const int kRemoteGuidsFieldNumber = 7;
  inline ::google::protobuf::uint32 remoteguids(int index) const;
  inline void set_remoteguids(int index, ::google::protobuf::uint32 value);
  inline void add_remoteguids(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      remoteguids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_remoteguids();

  // repeated uint32 recvPlayerIDs = 8;
  inline int recvplayerids_size() const;
  inline void clear_recvplayerids();
  static const int kRecvPlayerIDsFieldNumber = 8;
  inline ::google::protobuf::uint32 recvplayerids(int index) const;
  inline void set_recvplayerids(int index, ::google::protobuf::uint32 value);
  inline void add_recvplayerids(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      recvplayerids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_recvplayerids();

  // optional uint32 ackSequenceNumber = 9;
  inline bool has_acksequencenumber() const;
  inline void clear_acksequencenumber();
  static const int kAckSequenceNumberFieldNumber = 9;
  inline ::google::protobuf::uint32 acksequencenumber() const;
  inline void set_acksequencenumber(::google::protobuf::uint32 value);

  // optional uint32 sequenceNumber = 10;
  inline bool has_sequencenumber() const;
  inline void clear_sequencenumber();
  static const int kSequenceNumberFieldNumber = 10;
  inline ::google::protobuf::uint32 sequencenumber() const;
  inline void set_sequencenumber(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pb.Header)
 private:
  inline void set_has_packetid();
  inline void clear_has_packetid();
  inline void set_has_packetsize();
  inline void clear_has_packetsize();
  inline void set_has_sourceguid();
  inline void clear_has_sourceguid();
  inline void set_has_playerid();
  inline void clear_has_playerid();
  inline void set_has_gateguid();
  inline void clear_has_gateguid();
  inline void set_has_playerguid();
  inline void clear_has_playerguid();
  inline void set_has_acksequencenumber();
  inline void clear_has_acksequencenumber();
  inline void set_has_sequencenumber();
  inline void clear_has_sequencenumber();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 packetid_;
  ::google::protobuf::int32 packetsize_;
  ::google::protobuf::uint32 sourceguid_;
  ::google::protobuf::uint32 playerid_;
  ::google::protobuf::uint32 gateguid_;
  ::google::protobuf::uint32 playerguid_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > remoteguids_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > recvplayerids_;
  ::google::protobuf::uint32 acksequencenumber_;
  ::google::protobuf::uint32 sequencenumber_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];

  friend void  protobuf_AddDesc_header_2eproto();
  friend void protobuf_AssignDesc_header_2eproto();
  friend void protobuf_ShutdownFile_header_2eproto();

  void InitAsDefaultInstance();
  static Header* default_instance_;
};
// ===================================================================


// ===================================================================

// Header

// optional int32 packetID = 1;
inline bool Header::has_packetid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Header::set_has_packetid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Header::clear_has_packetid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Header::clear_packetid() {
  packetid_ = 0;
  clear_has_packetid();
}
inline ::google::protobuf::int32 Header::packetid() const {
  return packetid_;
}
inline void Header::set_packetid(::google::protobuf::int32 value) {
  set_has_packetid();
  packetid_ = value;
}

// optional int32 packetSize = 2;
inline bool Header::has_packetsize() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Header::set_has_packetsize() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Header::clear_has_packetsize() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Header::clear_packetsize() {
  packetsize_ = 0;
  clear_has_packetsize();
}
inline ::google::protobuf::int32 Header::packetsize() const {
  return packetsize_;
}
inline void Header::set_packetsize(::google::protobuf::int32 value) {
  set_has_packetsize();
  packetsize_ = value;
}

// optional uint32 sourceGuid = 3;
inline bool Header::has_sourceguid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Header::set_has_sourceguid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Header::clear_has_sourceguid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Header::clear_sourceguid() {
  sourceguid_ = 0u;
  clear_has_sourceguid();
}
inline ::google::protobuf::uint32 Header::sourceguid() const {
  return sourceguid_;
}
inline void Header::set_sourceguid(::google::protobuf::uint32 value) {
  set_has_sourceguid();
  sourceguid_ = value;
}

// optional uint32 playerID = 4;
inline bool Header::has_playerid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Header::set_has_playerid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Header::clear_has_playerid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Header::clear_playerid() {
  playerid_ = 0u;
  clear_has_playerid();
}
inline ::google::protobuf::uint32 Header::playerid() const {
  return playerid_;
}
inline void Header::set_playerid(::google::protobuf::uint32 value) {
  set_has_playerid();
  playerid_ = value;
}

// optional uint32 gateGuid = 5;
inline bool Header::has_gateguid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Header::set_has_gateguid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Header::clear_has_gateguid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Header::clear_gateguid() {
  gateguid_ = 0u;
  clear_has_gateguid();
}
inline ::google::protobuf::uint32 Header::gateguid() const {
  return gateguid_;
}
inline void Header::set_gateguid(::google::protobuf::uint32 value) {
  set_has_gateguid();
  gateguid_ = value;
}

// optional uint32 playerGuid = 6;
inline bool Header::has_playerguid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Header::set_has_playerguid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Header::clear_has_playerguid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Header::clear_playerguid() {
  playerguid_ = 0u;
  clear_has_playerguid();
}
inline ::google::protobuf::uint32 Header::playerguid() const {
  return playerguid_;
}
inline void Header::set_playerguid(::google::protobuf::uint32 value) {
  set_has_playerguid();
  playerguid_ = value;
}

// repeated uint32 remoteGuids = 7;
inline int Header::remoteguids_size() const {
  return remoteguids_.size();
}
inline void Header::clear_remoteguids() {
  remoteguids_.Clear();
}
inline ::google::protobuf::uint32 Header::remoteguids(int index) const {
  return remoteguids_.Get(index);
}
inline void Header::set_remoteguids(int index, ::google::protobuf::uint32 value) {
  remoteguids_.Set(index, value);
}
inline void Header::add_remoteguids(::google::protobuf::uint32 value) {
  remoteguids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Header::remoteguids() const {
  return remoteguids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Header::mutable_remoteguids() {
  return &remoteguids_;
}

// repeated uint32 recvPlayerIDs = 8;
inline int Header::recvplayerids_size() const {
  return recvplayerids_.size();
}
inline void Header::clear_recvplayerids() {
  recvplayerids_.Clear();
}
inline ::google::protobuf::uint32 Header::recvplayerids(int index) const {
  return recvplayerids_.Get(index);
}
inline void Header::set_recvplayerids(int index, ::google::protobuf::uint32 value) {
  recvplayerids_.Set(index, value);
}
inline void Header::add_recvplayerids(::google::protobuf::uint32 value) {
  recvplayerids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Header::recvplayerids() const {
  return recvplayerids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Header::mutable_recvplayerids() {
  return &recvplayerids_;
}

// optional uint32 ackSequenceNumber = 9;
inline bool Header::has_acksequencenumber() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Header::set_has_acksequencenumber() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Header::clear_has_acksequencenumber() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Header::clear_acksequencenumber() {
  acksequencenumber_ = 0u;
  clear_has_acksequencenumber();
}
inline ::google::protobuf::uint32 Header::acksequencenumber() const {
  return acksequencenumber_;
}
inline void Header::set_acksequencenumber(::google::protobuf::uint32 value) {
  set_has_acksequencenumber();
  acksequencenumber_ = value;
}

// optional uint32 sequenceNumber = 10;
inline bool Header::has_sequencenumber() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Header::set_has_sequencenumber() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Header::clear_has_sequencenumber() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Header::clear_sequencenumber() {
  sequencenumber_ = 0u;
  clear_has_sequencenumber();
}
inline ::google::protobuf::uint32 Header::sequencenumber() const {
  return sequencenumber_;
}
inline void Header::set_sequencenumber(::google::protobuf::uint32 value) {
  set_has_sequencenumber();
  sequencenumber_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_header_2eproto__INCLUDED
